### ISSUE TITLE
Swin Tranning Error

### ISSUE THREAD

**Issue by tintranrynan** [JDAI-CV/FaceX-Zoo#122]
Thank you for this project
I have some errors when training with Swin-Trans
I have all requirements and using GTX1070Ti 8Gb but I cannot train. You can see it below. Please help me

Use GPU: 0 for training
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    train(args)
  File "train.py", line 120, in train
    dist.init_process_group(backend='nccl', init_method='env://')
  File "/home/tintran/anaconda3/envs/env04_facezoo_swin/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 436, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/tintran/anaconda3/envs/env04_facezoo_swin/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 179, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/tintran/anaconda3/envs/env04_facezoo_swin/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tintran/anaconda3/envs/env04_facezoo_swin/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tintran/anaconda3/envs/env04_facezoo_swin/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/tintran/anaconda3/envs/env04_facezoo_swin/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command

**Comment by wang21jun** [comment]
Please note: "RuntimeError: Address already in use“
That is the master_port is in use, please modify the port to another one, such as: --master_port=1334

**Comment by tintranrynan** [comment]
Thank you for helping me.
Happy new year!

Vào Th 6, 31 thg 12, 2021 vào lúc 09:46 wang21jun <
***@***.***> đã viết:
