### ISSUE TITLE
semi-siamese_training problem

### ISSUE THREAD

**Issue by YjDai** [JDAI-CV/FaceX-Zoo#37]
I use my dataset for training.There is a probelm.

Traceback (most recent call last):
  File "train.py", line 186, in <module>
    train(args)
  File "train.py", line 130, in train
    prototype, optimizer, criterion, epoch, conf, loss_meter)
  File "train.py", line 69, in train_one_epoch
    images1_probe = probe_net(images1)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../../backbone/MobileFaceNets.py", line 102, in forward
    out = self.conv_6_dw(out)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../../backbone/MobileFaceNets.py", line 41, in forward
    x = self.bn(x)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/home/dl/dyj/venv37/lib/python3.7/site-packages/torch/nn/functional.py", line 1666, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1])

**Comment by wang21jun** [comment]
Maybe you can refer to https://www.cnblogs.com/zmbreathing/p/pyTorch_BN_error.html
