### ISSUE TITLE
semi-siamese training with custom dataset problem

### ISSUE THREAD

**Issue by mchllandrea** [JDAI-CV/FaceX-Zoo#63]
What I did:
1. Downloaded LFW funnelled dataset, used FMA-3D to apply mask to the images
2. Train & test split, chose only 2 images per identity
3. Generated a text file lfw_train2.txt (file name + class) --> the class corresponds to the identity of the image (e.g. 0: Michael Jackson)
    Example: 
    Aaron_Peirsol/Aaron_Peirsol_0001.jpg 0
    Aaron_Peirsol/Aaron_Peirsol_0002.jpg 0
    Aaron_Sorkin/Aaron_Sorkin_0001.jpg 1
    Aaron_Sorkin/Aaron_Sorkin_0002.jpg 1
4. Made the following changes to train.sh:
    --data_root '../../addition_module/face_mask_adding/FMA-3D/data/masked_dataset_train_shallow' \
    --train_file '../../addition_module/face_mask_adding/FMA-3D/data/files/lfw_train2.txt' \
5. Made the following changes to head_conf.yaml:
    SST_Prototype:
         queue_size: 2688 #is divisible by batch size.
6. Run sh train.sh

Error:
`INFO 2021-04-07 23:38:32 train.py: 160] Start optimization.
INFO 2021-04-07 23:38:32 train.py: 161] Namespace(alpha=0.999, backbone_conf_file='../backbone_conf.yaml', backbone_type='MobileFaceNet', batch_size=128, data_root='../../addition_module/face_mask_adding/FMA-3D/data/masked_dataset_train_shallow', epoches=250, head_conf_file='../head_conf.yaml', head_type='SST_Prototype', log_dir='log', lr=0.1, milestones=[150, 200, 230], momentum=0.9, out_dir='out_dir', pretrain_model='mv_epoch_8.pt', print_freq=100, resume=False, save_freq=10, step='150,200,230', tensorboardx_logdir='sst_mobileface', train_file='../../addition_module/face_mask_adding/FMA-3D/data/files/lfw_train2.txt', writer=<tensorboardX.writer.SummaryWriter object at 0x7f5b12e477b8>)
backbone param:
{'feat_dim': 512, 'out_h': 7, 'out_w': 7}
head param:
{'feat_dim': 512, 'queue_size': 2688, 'scale': 32.0, 'loss_type': 'am_softmax', 'margin': 0.35}
Valid ids: 1344.
../../backbone/backbone_def.py:29: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  backbone_conf = yaml.load(f)
../../head/head_def.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  head_conf = yaml.load(f)
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    train(args)
  File "train.py", line 125, in train
    prototype, optimizer, criterion, epoch, conf, loss_meter)
  File "train.py", line 65, in train_one_epoch
    images1_probe = probe_net(images1)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../../backbone/MobileFaceNets.py", line 104, in forward
    out = self.linear(out)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/students/acct2014_07/URECA/facereg/lib/python3.6/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0`

What did I do wrong?

**Comment by wang21jun** [comment]
Before send the images to the network, you should crop them to 112*112.
